"""
Token-related constants for the OOD detection project.
"""

# Special tokens
REST = 27512
SEP = 55025
AR = 55026
AAR = 55027

# Token offsets (not anticipated)
TIME_OFFSET = 0
DUR_OFFSET = 10000
NOTE_OFFSET = 11000
VELOCITY_OFFSET = 55028

# Token offsets (anticipated)
ATIME_OFFSET = 27513
ADUR_OFFSET = 37513
ANOTE_OFFSET = 38513
AVELOCITY_OFFSET = 55156

TIME_RESOLUTION = 100
MAX_DURATION_IN_SECONDS = 10

MAX_DUR = TIME_RESOLUTION * MAX_DURATION_IN_SECONDS
MAX_INSTR = 129
MAX_PITCH = 128
MAX_NOTE = MAX_PITCH * MAX_INSTR
MAX_VELOCITY = 128

# Vocabulary settings
INCLUDE_VELOCITY = False
VOCAB_SIZE = VELOCITY_OFFSET + 256 if INCLUDE_VELOCITY else VELOCITY_OFFSET

# Note names
NOTES = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]
